### ISSUE TITLE
Add page with container access information

### ISSUE THREAD

**Issue by tsalo** [ABCD-ReproNim/materials#18]
Could call the page "Resources" with links to a range of Google Docs. Pinging @satra and @angielaird about structure and content. I can handle adding the page.

**Comment by angielaird** [comment]
Yes, I agree to call it "Resources". We should link to existing gdocs on

**Comment by angielaird** [comment]
Yes, I agree we should call this "Resources". We can also link to existing gdocs on Data Access Instructions, ABCD Data Access Document, JupyterHub Introduction.

**Comment by tsalo** [comment]
The Data Access document appears to be restricted access. I didn't touch the permissions in case it's supposed to be like that.

Are there any other documents you want listed on this page?
