### ISSUE TITLE
A couple of tweek suggestions

### ISSUE THREAD

**Issue by dnkennedy** [ABCD-ReproNim/materials#2]
On the weekly page (for example, https://abcd-repronim.github.io/materials/week-1/):
We point to the "Question & Answer Doc".  Could we add just a bit of explanation, such as:
"[Question & Answer Doc](https://docs.google.com/document/d/14NLnourpjasNaJw8HjAQXDXruULLYN4NK-yNzY0K1Xo/edit) - Enter questions here for discussion during the 'Instructor Question & Answer Livestream' "

Should we include the date/time for the 'Instructor Question & Answer Livestream', which is then followed by the observer and enrolled student routes you have.

**Comment by tsalo** [comment]
@richford handled the first part. I added the second in 5408e2b. Thank you!
