### ISSUE TITLE
Update Week 2 materials page after Q&A airing

### ISSUE THREAD

**Issue by jessicabartley** [ABCD-ReproNim/materials#5]
Add youtube video of the Q&A recording: https://youtu.be/xcgDafWEBM8
Update any other conditional formatting that is needed

**Comment by tsalo** [comment]
We just need to add the embedded version of the URL (can be accessed via "Share" button, the "Embed"), which is https://www.youtube.com/embed/xcgDafWEBM8, to `qa_video:` in `_posts/2020-10-23-week-2.md`.

**Comment by jessicabartley** [comment]
Shouldn't we also update the text to say (similar to Week 1) "the Q&A session for this week has ended...." and so on?

**Comment by tsalo** [comment]
That's actually handled with an if statement. If `qa_video` is set, then that text is rendered instead of the default. See here:

https://github.com/ABCD-ReproNim/materials/blob/8935664bec2fd379cf5839266ba9fc4094c53f48/_layouts/post.html#L18-L22

**Comment by jessicabartley** [comment]
Excellent. Thanks @tsalo. I'll make the changes and submit a pull request.

**Comment by tsalo** [comment]
Closed by #7.
