### ISSUE TITLE
Force closed captioning on embedded youtube videos

### ISSUE THREAD

**Issue by jessicabartley** [ABCD-ReproNim/materials#6]
I believe this is possible, as described [here](https://support.automaticsync.com/hc/en-us/articles/115002362403-How-to-force-Closed-Captions-to-appear-on-YouTube-videos-you-own)

Edits needed would be by editing the embed code: open the video on a separate tab, click Share (under the video), and open the Embed section. Copy the embed code and add ?cc_load_policy=1 at the end of the URL

**Comment by tsalo** [comment]
I think we could just change the layout in the following locations to append `?cc_load_policy=1` to the URL:

https://github.com/ABCD-ReproNim/materials/blob/8935664bec2fd379cf5839266ba9fc4094c53f48/_layouts/post.html#L84

https://github.com/ABCD-ReproNim/materials/blob/8935664bec2fd379cf5839266ba9fc4094c53f48/_layouts/post.html#L136

https://github.com/ABCD-ReproNim/materials/blob/8935664bec2fd379cf5839266ba9fc4094c53f48/_layouts/post.html#L189
