### ISSUE TITLE
Add extra demo videos

### ISSUE THREAD

**Issue by jessicabartley** [ABCD-ReproNim/materials#9]
Closes #9

We have an extra demo video for Week 3. We would like to add _under_ the main ReproNim Week 3 lecture video (not at the top of the page). This may require either modifying how extra material are displayed to select either top or bottom of page, or potentially updating the videos and lecture pdf fields to accept list inputs.

**Comment by tsalo** [comment]
You should be able to open a PR with the content change(s) now.

**Comment by tsalo** [comment]
Should have been closed by #11.
